version: "3.9"

services:

  bankease-mysql:
    image: mysql:8.0
    container_name: bankease-mysql
    environment:
      MYSQL_DATABASE: bankease
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    ports:
      - "3307:3306"
    volumes:
      - bankease-data:/var/lib/mysql

  bankease:
    build: .
    container_name: bankease
    depends_on:
      - bankease-mysql
    ports:
      - "8080:8080"
      - "4848:4848"
    environment:
      DB_HOST: bankease-mysql
      DB_NAME: bankease
      DB_USER: bankuser
      DB_PASS: bankpass

volumes:
  bankease-data:
